/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_engagemobile_vsfootball_natives_Core */

#ifndef _Included_com_engagemobile_vsfootball_natives_Core
#define _Included_com_engagemobile_vsfootball_natives_Core
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_engagemobile_vsfootball_natives_Core
 * Method:    LibMain
 * Signature: ([Ljava/lang/String;Landroid/content/res/AssetManager;)I
 */
JNIEXPORT jint JNICALL Java_com_engagemobile_vsfootball_natives_Core_LibMain
  (JNIEnv *, jclass, jobjectArray, jobject);

/*
 * Class:     com_engagemobile_vsfootball_natives_Core
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_engagemobile_vsfootball_natives_Core_start
  (JNIEnv *, jclass);

/*
 * Class:     com_engagemobile_vsfootball_natives_Core
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_engagemobile_vsfootball_natives_Core_stop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
